---
title: "M4 Homework"
author: "Warrenkevin B Henderson"
date: "9/13/2021"
output:
  html_document: default
  pdf_document: default
---

### Challenge1
## Frank Short Peer Commentary
```{r}
#Files need to be named "BUlogin_OriginalHomeworkCode_01" for first one and "BUlogin_FinalHomeworkCode_01" for when it's submitted.

#You also need to "knit" the R markdown (see the button next to search in top right below markdown file name) for it to be saved as an html. This is how the R markdown is viewed by others via website / PDF.

library(stringr)
Vector_1<- c("Stately", "plump", "Buck", "Mulligan", "came", "from", "the", "stairhead", "bearing", "a", "bowl", "of", "lather", "on", "which", "a", "mirror", "and", "a", "razor", "lay", "crossed")
Vector_1[seq(from = 3, to = 22, by = 3)]

#The stringr package can be used to separate the full character string. You can do this by using str_split, separating via a space as " " and then putting simplify = TRUE to make sure it does not get turned into a list. 
```
### Challenge 2

```{r}
# It might be a good idea to put the instructions for each challenge before the code so that it is more easily understandable in the markdown file. You can put these instructions in the noncoding sections. 

m <- matrix(data = 1:80, nrow = 8, ncol = 10, byrow = FALSE)
m
x <- m[,c(2,3,6)]
x

x <- m[6:8]
x

x <- m[2:6,2:9]
x
```
### Challenge 3

```{r}
a <- array(data = 400:1, dim = c(5, 5, 4, 4))
a
a[1, 1, 1, 2]
a[2,3,2,]
a[1:5, 1:5, 3, 3]
```

### Challenge 4
```{r}
Catarrhini <- c("Cercopithecidae","Hylobatidae","Hominidae")
Platyrrhini <- c("Cebidae", "Atelidae", "Pitheciidae")
Anthropoidea <- list(Platyrrhini, Catarrhini)
names(Anthropoidea) <- list("Platyrrhini","Catarrhini")
Anthropoidea
Tarsioidea <- c("Tarsiidae")
Tarsioidea
Haplorhini <- list(Anthropoidea, Tarsioidea)
names(Haplorhini) <- list("Anthropoidea", "Tarsioidea")
Haplorhini
Lemuroidea <- c("Cheirogaleidae", "Lepilemuridae", "Indriidae", "Lemuridae",
    "Daubentoniidae")
Lorisoidea <- c("Lorisidae", "Galagidae")
Strepsirhini <- list(Lemuroidea, Lorisoidea)
names(Strepsirhini) <- list("Lemuroidea", "Lorisoidea")
Strepsirhini
Primate <- list(Haplorhini, Strepsirhini)
names(Primate) <- list("Haplorhini", "Strepsirhini")
Primate
```

### Challenge 5

```{r}
library(stringi)
# Don't need to call stringi here. 

m3 <- matrix(data = c(3, 0, 1 ,23, 1, 2, 33, 1, 1, 42, 0, 1, 41, 0, 2), nrow = 5, ncol = 3, byrow = TRUE)
m3 <- as.data.frame(m3)
colnames(m3)
m3[,2] <- as.logical(m3$V2)
m3[,3] <- as.factor(m3$V3)
str(m3)
```